# Generated by Django 3.2.5 on 2022-04-08 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Chromosone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_coordinate', models.IntegerField()),
                ('end_coordinate', models.IntegerField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Interval', to='genes.build')),
                ('chromosone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Interval', to='genes.chromosone')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Interval', to='genes.gene')),
            ],
        ),
    ]
